import { z } from 'zod';

/** Identifier of a stored media item. Generated by the server as a UUID. */
export const mediaIdSchema = z.uuid();

export type MediaId = z.infer<typeof mediaIdSchema>;

/** Timestamps are exchanged as ISO 8601 strings in UTC. */
export const isoTimestampSchema = z.iso.datetime();

export type IsoTimestamp = z.infer<typeof isoTimestampSchema>;

/** A cursor is opaque to API consumers and must only be passed back unchanged. */
export const paginationCursorSchema = z.string().min(1).max(512);

export type PaginationCursor = z.infer<typeof paginationCursorSchema>;
