import { randomUUID } from 'node:crypto';
import { constants } from 'node:fs';
import {
  access,
  mkdir,
  open,
  readdir,
  rename,
  rm,
  unlink,
} from 'node:fs/promises';
import { join } from 'node:path';

/** Directory names created inside the configured data directory. */
export const MEDIA_DIRECTORY_NAME = 'media';
export const TEMPORARY_DIRECTORY_NAME = 'tmp';

/**
 * Stored file names are generated by the server, never by a client, so a strict
 * allowlist is enough to keep every path inside the media directory.
 */
const STORED_FILENAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$/u;

export class UnsafeStoredFilenameError extends Error {
  constructor(storedFilename: string) {
    super(`Refusing to use an unsafe stored file name: ${storedFilename}`);
    this.name = 'UnsafeStoredFilenameError';
  }
}

const assertSafeStoredFilename = (storedFilename: string): void => {
  if (
    !STORED_FILENAME_PATTERN.test(storedFilename) ||
    storedFilename === '.' ||
    storedFilename === '..' ||
    storedFilename.includes('..')
  ) {
    throw new UnsafeStoredFilenameError(storedFilename);
  }
};

const isMissingFileError = (error: unknown): boolean =>
  error instanceof Error && (error as NodeJS.ErrnoException).code === 'ENOENT';

/** Makes a rename durable so a crash cannot leave the directory entry unwritten. */
const syncDirectory = async (directory: string): Promise<void> => {
  const handle = await open(directory, constants.O_RDONLY);

  try {
    await handle.sync();
  } catch (error) {
    // Some platforms reject fsync on a directory handle; durability of the
    // rename is best effort there and the file contents are already synced.
    if ((error as NodeJS.ErrnoException).code !== 'EINVAL') {
      throw error;
    }
  } finally {
    await handle.close();
  }
};

/**
 * A file being written outside the media directory. Exactly one of `commit` or
 * `discard` takes effect; both are safe to call more than once so a request
 * handler can always discard in a `finally` block.
 */
export interface TemporaryMediaFile {
  readonly path: string;
  commit(storedFilename: string): Promise<string>;
  discard(): Promise<void>;
}

export interface MediaStorage {
  readonly rootDirectory: string;
  readonly mediaDirectory: string;
  readonly temporaryDirectory: string;
  initialize(): Promise<void>;
  createTemporaryFile(): Promise<TemporaryMediaFile>;
  resolveMediaPath(storedFilename: string): string;
  exists(storedFilename: string): Promise<boolean>;
  remove(storedFilename: string): Promise<boolean>;
  pruneTemporaryFiles(): Promise<number>;
}

/**
 * Local media storage. The temporary directory lives inside the data directory
 * so promoting a finished upload is a same-filesystem rename, which is atomic:
 * the media directory never contains a partially written file.
 */
export const createMediaStorage = (rootDirectory: string): MediaStorage => {
  const mediaDirectory = join(rootDirectory, MEDIA_DIRECTORY_NAME);
  const temporaryDirectory = join(rootDirectory, TEMPORARY_DIRECTORY_NAME);

  const resolveMediaPath = (storedFilename: string): string => {
    assertSafeStoredFilename(storedFilename);
    return join(mediaDirectory, storedFilename);
  };

  return {
    rootDirectory,
    mediaDirectory,
    temporaryDirectory,

    initialize: async () => {
      await mkdir(rootDirectory, { recursive: true, mode: 0o700 });
      await mkdir(mediaDirectory, { recursive: true, mode: 0o700 });
      await mkdir(temporaryDirectory, { recursive: true, mode: 0o700 });
    },

    createTemporaryFile: async () => {
      await mkdir(temporaryDirectory, { recursive: true, mode: 0o700 });

      const path = join(temporaryDirectory, `${randomUUID()}.part`);
      let settled = false;

      return {
        path,

        commit: async (storedFilename) => {
          const target = resolveMediaPath(storedFilename);

          if (settled) {
            throw new Error(
              'The temporary media file has already been committed or discarded',
            );
          }

          const handle = await open(path, constants.O_RDONLY);

          try {
            await handle.sync();
          } finally {
            await handle.close();
          }

          await rename(path, target);
          settled = true;
          await syncDirectory(mediaDirectory);

          return target;
        },

        discard: async () => {
          if (settled) {
            return;
          }

          settled = true;

          try {
            await unlink(path);
          } catch (error) {
            if (!isMissingFileError(error)) {
              throw error;
            }
          }
        },
      };
    },

    resolveMediaPath,

    exists: async (storedFilename) => {
      try {
        await access(resolveMediaPath(storedFilename), constants.R_OK);
        return true;
      } catch (error) {
        if (isMissingFileError(error)) {
          return false;
        }

        throw error;
      }
    },

    remove: async (storedFilename) => {
      try {
        await unlink(resolveMediaPath(storedFilename));
        return true;
      } catch (error) {
        if (isMissingFileError(error)) {
          return false;
        }

        throw error;
      }
    },

    /** Removes leftovers from uploads interrupted by a crash or restart. */
    pruneTemporaryFiles: async () => {
      let entries: string[];

      try {
        entries = await readdir(temporaryDirectory);
      } catch (error) {
        if (isMissingFileError(error)) {
          return 0;
        }

        throw error;
      }

      let removed = 0;

      for (const entry of entries) {
        await rm(join(temporaryDirectory, entry), {
          recursive: true,
          force: true,
        });
        removed += 1;
      }

      return removed;
    },
  };
};
